### ISSUE TITLE
Local wpk configuration, e.g. `.wpkrc`

### ISSUE THREAD

**Issue by sdgluck** [wpk-cli/wpk#4]
Although the global user config is nice for the individual developer, when working in teams it may be desirable for the team to use the same config. In this case the global config is not practical.

A `.wpkrc` config file that is merged into the global user config would be nice. The local config taken precedence over the global config.

Are there some options that should not be merged? e.g. presets

**Comment by kucukkanat** [comment]
I dont think a config file for a cli to generate/manage another config file is a good idea. Isn't the whole point not having to deal with these anyway?

**Comment by sdgluck** [comment]
I think you're right. It would be overkill. Cheers
